{% set version = "0.1.2" %}

package:
  name: anaconda-linter
  version: {{ version }}

source:
  fn: anaconda-linter-{{ version }}.tar.gz
  url: https://github.com/anaconda-distribution/anaconda-linter/archive/{{ version }}.tar.gz
  sha256: b42afa8558fc4e06fa8a216bf5952bf5ce15d688c871748787746d3d28727a25

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - conda-lint = anaconda_linter.run:main
    - anaconda-lint = anaconda_linter.run:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - requests
    - ruamel.yaml
    - license-expression
    - jinja2
    - conda-build
    - jsonschema
    - networkx
    - percy >=0.1.1,<0.2.0

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - anaconda_linter
    - anaconda_linter.lint
  commands:
    - pip check
    # Check entry points
    - anaconda-lint -h
    - conda-lint -h
    # lint_list is only an important test for development
    - python -m pytest tests -k "not lint_list"

about:
  home: https://github.com/anaconda-distribution/anaconda-linter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A conda feedstock linter written in pure Python.
  description: |
    Runs a range of static checks on conda feedstocks. Under
    ongoing development.
  doc_url: https://github.com/anaconda-distribution/anaconda-linter/blob/main/README.md
  dev_url: https://github.com/anaconda-distribution/anaconda-linter

extra:
  recipe-maintainers:
    - marcoesters
    - schuylermartin45
