{% set version = "0.1.6" %}

package:
  name: anaconda-linter
  version: {{ version }}

source:
  url: https://github.com/anaconda/anaconda-linter/archive/{{ version }}.tar.gz
  sha256: 341c8666e7760ef666fc146edad9a5ffe56ca08bc72d4f9a28845cc2b0fc8dbc

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - conda-lint = anaconda_linter.run:main
    - anaconda-lint = anaconda_linter.run:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - requests
    - ruamel.yaml
    - license-expression
    - jinja2
    - conda-build
    - jsonschema
    - networkx
    - percy >=0.1.5

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-xdist
  imports:
    - anaconda_linter
    - anaconda_linter.lint
  commands:
    - pip check
    # Check entry points
    - anaconda-lint -h
    - conda-lint -h
    # lint_list is only an important test for development
    - python -m pytest -n auto tests -k "not lint_list"

about:
  home: https://github.com/anaconda/anaconda-linter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A conda feedstock linter written in pure Python.
  description: |
    Runs a range of static checks on conda feedstocks. Under
    ongoing development.
  doc_url: https://github.com/anaconda/anaconda-linter/blob/main/README.md
  dev_url: https://github.com/anaconda/anaconda-linter

extra:
  skip-lints:
    - avoid_noarch
  recipe-maintainers:
    - marcoesters
    - schuylermartin45
