{% set version = "0.0.1" %}

package:
  name: anaconda-linter
  version: {{ version }}

source:
  fn: anaconda-linter-{{ version }}.tar.gz
  url: https://github.com/anaconda-distribution/anaconda-linter/archive/{{ version }}.tar.gz
  sha256: c0004740a8ca22041ca284e486d228c12577bc4f51de4f2e5f4b36509dec4764

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - ruamel.yaml
    - pyyaml
    - license-expression
    - jinja2
    - tqdm
    - conda-build
    - jsonschema
    - networkx

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-html
  commands:
    - python -m pytest -vv tests
